### ISSUE TITLE
message.align('center') does not work

### ISSUE THREAD

**Issue by blindler** [pydraw/pydraw#13]
message.align('center')
gives tkinter error:
                                                                                                
$ python3 /home/stu/stucode/main.py & echo $! > /tmp/running_program_pid
[1] 123
$ Traceback (most recent call last):
  File "/home/stu/stucode/main.py", line 7, in <module>
    message.align('center')
  File "/usr/local/lib/python3.8/dist-packages/pydraw/objects.py", line 4471, in align
    self._screen._canvas.itemconfigure(self._ref, align=self._aligns[self._align])
  File "<string>", line 1, in itemconfigure
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2903, in itemconfigure
    return self._configure(('itemconfigure', tagOrId), cnf, kw)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-align"

**Comment by noahcoetsee** [comment]
Uh oh.. tkinter changing with new version of Python maybe...

**Comment by noahcoetsee** [comment]
Will have fix included in next patch!
